add some ifs
git-svn-id: file:///home/SUBVERSION/jas/trunk@3901 eafcb37d-f50b-0410-b8f7-d4cb9effa109

diff --git a/jas b/jas
--- a/jas
+++ b/jas
@@ -1,12 +1,53 @@
 #!/bin/bash
-# $Id: $
+# $Id$
 #
 SCRIPT_LANG="python"
 SCRIPT_LANG="ruby"
 #
-JAVA_LIBS="../lib/log4j.jar:../lib/junit.jar:../lib/jas.jar"
+DEBUG=0
 #
-JAVA_OPTS="-J-verbose:gc -J-Xms1100M -J-Xmx1900M"
+# setup required libs: JAVA_LIBS="../lib/log4j.jar:../lib/junit.jar:../lib/jas.jar"
+#
+if [ -f "../lib/log4j.jar" ] ; then
+   JAVA_LIBS="../lib/log4j.jar"
+elif [ -f "lib/log4j.jar" ] ; then
+   JAVA_LIBS="lib/log4j.jar"
+else
+   echo "===========================================" 
+   echo "Error: library log4j.jar not found" 
+   echo "Please install log4j.jar in lib/ or ../lib/" 
+   echo "===========================================" 
+   exit 0
+fi
+#
+if [ -f "../lib/junit.jar" ] ; then
+   JAVA_LIBS="$JAVA_LIBS:../lib/junit.jar"
+elif [ -f "lib/junit.jar" ] ; then
+   JAVA_LIBS="$JAVA_LIBS:lib/junit.jar"
+else
+   echo "===========================================" 
+   echo "Warning: library junit.jar not found" 
+   echo "Please install junit.jar in lib/ or ../lib/" 
+   echo "===========================================" 
+fi
+#
+if [ -f "../lib/jas.jar" ] ; then
+   JAVA_LIBS="$JAVA_LIBS:../lib/jas.jar"
+elif [ -f "lib/jas.jar" ] ; then
+   JAVA_LIBS="$JAVA_LIBS:lib/jas.jar"
+elif [ -f "jas.jar" ] ; then
+   JAVA_LIBS="$JAVA_LIBS:jas.jar"
+else
+   echo "===========================================" 
+   echo "Error: library jas.jar not found" 
+   echo "Please install jas.jar in lib/ or ../lib/" 
+   echo "===========================================" 
+   exit 0
+fi
+#
+#JAVA_OPTS="-J-verbose:gc -J-Xms1100M -J-Xmx1900M"
+JAVA_OPTS="-J-verbose:gc -J-Xms350M -J-Xmx800M"
+#JAVA_OPTS="-J-verbose:gc"
 #
 # check for scripting language
 # Scanning for args is aborted by '--'.
@@ -26,6 +67,9 @@ do
     -h|--help)
          help_requested=true
          ;;
+    -d|--verbose)
+         DEBUG=1
+         ;;
     --) break ;;
     # Other opts go through  
     -*) jas_args=("${jas_args[@]}" "$1") ;;
@@ -44,16 +88,18 @@ if [ -n "$help_requested" ] ; then
   echo "JAS options:" >&2
   echo "-py|-jy   : use Python scripting with jython" >&2
   echo "-rb|-jr   : use Ruby scripting with jruby" >&2
+  echo "-d        : debug this script" >&2
   echo "-h|--help : this infos" >&2
   echo "--        : pass remaining arguments through to Jython|JRuby" >&2
-  exit
+  exit 0
 fi
 
 #
 if [ "$SCRIPT_LANG" = "python" ]; then
-   #jython -v -J-verbose -J-client -J-cp "$JAVA_LIBS" $JAVA_OPTS $jas_args $* 
+   [[ $DEBUG > 0 ]] && echo jython -J-cp "$JAVA_LIBS" $JAVA_OPTS $* 
    jython -J-cp "$JAVA_LIBS" $JAVA_OPTS $* 
 elif [ "$SCRIPT_LANG" = "ruby" ]; then
+   [[ $DEBUG > 0 ]] && echo jruby -J-cp "$JAVA_LIBS" $JAVA_OPTS -S jirb -r "examples/jas" $*
    jruby -J-cp "$JAVA_LIBS" $JAVA_OPTS -S jirb -r "examples/jas" $*
 fi
 #
